import Header from "../components/Header";
import "./global.css";
import { Ubuntu } from "next/font/google";

const ubuntu = Ubuntu({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
